# -*- coding: utf-8 -*-
"""preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qO18cih6E9920RxWwYq5fBnDrswdh0uQ
"""

import pandas as pd

dataset2=pd.read_excel(r'/content/drive/MyDrive/boston_data (4)(2).xlsx')
dataset2

dataset2['category'].unique()

# Replace NaN in 'model' column with 'no specific model'
dataset2['model'] = dataset2['model'].fillna('no specific model')

# Verify changes
#print(dataset2['model'].unique())
dataset2

dataset2['model'] = dataset2['model'].str.split(', ')
dataset2 = dataset2.explode('model', ignore_index=True)

import re

def extract_main_name(title):

  parts = re.split(r'[,:;|\-.]', title)
  if parts:
    return parts[0].strip()
  else:
    return title

dataset2['main_name'] = dataset2['product_title'].apply(extract_main_name)

dataset2['Is_accessory'] = dataset2['Is_accessory'].fillna(False)
dataset2

dataset2 = dataset2.dropna()
dataset2 = dataset2.reset_index(drop=True)

dataset2.isnull().sum()

dataset2 = dataset2[dataset2['price'] != 'Not Available']
len(dataset2['price'])

# Convert 'price' column to numeric by removing commas and '.00'
dataset2['price'] = dataset2['price'].astype(str).str.replace(',', '').str.replace('.00', '', regex=False)
len(dataset2['price'])

dataset2['price']=dataset2['price'].astype(int)

dataset2['rating'].unique()

dataset2['rating'] = dataset2['rating'].apply(lambda x: float(str(x).split(' out of ')[0]) if 'out of' in str(x) else float(x))
print(dataset2['rating'])

dataset2['rating'].unique()

dataset2['review_count'].unique()

dataset2['review_count'] = dataset2['review_count'].astype(str).str.replace(',', '').str.replace('ratings', '', regex=False).str.replace('rating', '', regex=False)
dataset2['review_count'] = dataset2['review_count'].astype(int)

def preprocess_features(features):
    # Remove "Brand:", "Model Name:", etc., and extra spaces
    cleaned = re.sub(r'(\w+):', r'\1', features)
    cleaned = re.sub(r'\s*;\s*', ', ', cleaned)  # Replace ';' with ', '
    cleaned = cleaned.strip()
    return cleaned

# Apply preprocessing
dataset2['features'] = dataset2['features'].apply(preprocess_features)

dataset2.info()

dataset2.isnull().sum()

dataset2.to_csv('dataset.csv',encoding='utf-8')

from google.colab import files

# Replace 'your_file.csv' with your file name
files.download('dataset.csv')

